// Auto-generated sidebar configuration
// Generated on 2025-06-01T04:20:54.670Z

const sidebars = {
  "tutorialSidebar": [
    {
      "type": "category",
      "label": "IGCSE",
      "items": [
        {
          "type": "category",
          "label": "Business Studies",
          "link": {
            "type": "generated-index",
            "title": "IGCSE Business Studies",
            "description": "Complete IGCSE Business Studies notes and resources",
            "slug": "/igcse/business"
          },
          "items": [
            {
              "type": "autogenerated",
              "dirName": "igcse/business"
            }
          ]
        },
        {
          "type": "category",
          "label": "Economics",
          "link": {
            "type": "generated-index",
            "title": "IGCSE Economics",
            "description": "Complete IGCSE Economics notes and resources",
            "slug": "/igcse/economics"
          },
          "items": [
            {
              "type": "autogenerated",
              "dirName": "igcse/economics"
            }
          ]
        },
        {
          "type": "category",
          "label": "Mathematics",
          "link": {
            "type": "generated-index",
            "title": "IGCSE Mathematics",
            "description": "Complete IGCSE Mathematics notes and resources",
            "slug": "/igcse/mathematics"
          },
          "items": [
            {
              "type": "autogenerated",
              "dirName": "igcse/mathematics"
            }
          ]
        },
        {
          "type": "category",
          "label": "Physics",
          "link": {
            "type": "generated-index",
            "title": "IGCSE Physics",
            "description": "Complete IGCSE Physics notes and resources",
            "slug": "/igcse/physics"
          },
          "items": [
            {
              "type": "autogenerated",
              "dirName": "igcse/physics"
            }
          ]
        }
      ],
      "link": {
        "type": "doc",
        "id": "igcse/igcse-intro"
      }
    }
  ]
};

module.exports = sidebars;
