// Auto-generated sidebar configuration
// Generated on 2025-06-02T09:32:42.072Z

const sidebars = {
  "tutorialSidebar": [
    {
      "type": "category",
      "label": "IGCSE",
      "items": [
        {
          "type": "category",
          "label": "Business Studies",
          "link": {
            "type": "generated-index",
            "title": "IGCSE Business Studies",
            "description": "Complete IGCSE Business Studies notes and resources",
            "slug": "/igcse/business"
          },
          "items": [
            {
              "type": "autogenerated",
              "dirName": "igcse/business"
            }
          ]
        },
        {
          "type": "category",
          "label": "Economics",
          "link": {
            "type": "generated-index",
            "title": "IGCSE Economics",
            "description": "Complete IGCSE Economics notes and resources",
            "slug": "/igcse/economics"
          },
          "items": [
            {
              "type": "autogenerated",
              "dirName": "igcse/economics"
            }
          ]
        },
        {
          "type": "category",
          "label": "Mathematics",
          "link": {
            "type": "generated-index",
            "title": "IGCSE Mathematics",
            "description": "Complete IGCSE Mathematics notes and resources",
            "slug": "/igcse/mathematics"
          },
          "items": [
            {
              "type": "autogenerated",
              "dirName": "igcse/mathematics"
            }
          ]
        },
        {
          "type": "category",
          "label": "Physics",
          "link": {
            "type": "generated-index",
            "title": "IGCSE Physics",
            "description": "Complete IGCSE Physics notes and resources",
            "slug": "/igcse/physics"
          },
          "items": [
            {
              "type": "category",
              "label": "Electricity and Magnetism",
              "link": {
                "type": "generated-index",
                "title": "Physics - Electricity and Magnetism",
                "description": "Electricity and Magnetism notes and resources for IGCSE Physics",
                "slug": "/igcse/physics/electricity-and-magnetism"
              },
              "items": [
                {
                  "type": "autogenerated",
                  "dirName": "igcse/physics/electricity-and-magnetism"
                }
              ]
            },
            {
              "type": "category",
              "label": "Thermal Physics",
              "link": {
                "type": "generated-index",
                "title": "Physics - Thermal Physics",
                "description": "Thermal Physics notes and resources for IGCSE Physics",
                "slug": "/igcse/physics/thermal-physics"
              },
              "items": [
                {
                  "type": "autogenerated",
                  "dirName": "igcse/physics/thermal-physics"
                }
              ]
            }
          ]
        }
      ],
      "link": {
        "type": "doc",
        "id": "igcse/igcse-intro"
      }
    }
  ]
};

module.exports = sidebars;
